version: '3.9'

services:
  db:
    image: postgres:16-alpine
    container_name: nest_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: nest
      POSTGRES_PASSWORD: nest
      POSTGRES_DB: nest
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  app:
    build:
      context: .
    container_name: nest_api
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "${PORT:-3000}:3000"
    volumes:
      - ./:/app
    command: npm run start:dev

volumes:
  db_data:
