
services:
  # PostgreSQL Database
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: uhBscN4gshrqiwJc
      POSTGRES_DB: s_pavilion
      TZ: Asia/Seoul
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d s_pavilion"]
      interval: 10s
      timeout: 5s
      retries: 5

    profiles:
      - mock
      - hardware
    networks:
      - s-pavilion-network
    restart: unless-stopped

  mock-modbus:
    build:
      context: ./mock-modbus
      dockerfile: Dockerfile
    container_name: mock-modbus
    ports:
      - "502:502"
    networks:
      - s-pavilion-network
    restart: unless-stopped
    command: python -u main.py
    volumes:
      - ./mock-modbus:/app
    profiles:
      - mock

  nest:
    image: node:22-alpine
    working_dir: /app
    environment:
      DATABASE_URL: postgresql://admin:uhBscN4gshrqiwJc@postgres:5432/s_pavilion
      PLC_PORT: /dev/ttyUSB0
      PLC_BAUD_RATE: 9600
      PLC_SLAVE_ID: 1
      NODE_ENV: development
      TZ: Asia/Seoul
      # Platform detection
      PLATFORM: ${PLATFORM:-windows}  # linux or windows
      
      # Windows Host Monitor (optional, for accessing real Windows host system info)
      HOST_MONITOR_URL: ${HOST_MONITOR_URL:-http://host.docker.internal:19100}
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    # Serial port device mapping for both Linux and Windows
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0  # PLC serial port (Linux)
      - /dev/ttyUSB1:/dev/ttyUSB1  # Additional serial port (Linux)
      - /dev/ttyACM0:/dev/ttyACM0  # Arduino/other serial devices (Linux)
      - /dev/ttyACM1:/dev/ttyACM1  # Additional Arduino devices (Linux)
    privileged: true  # Required for serial port access

    profiles:
      - default
      - hardware  # New profile for hardware access
      - mock  # Mock environment profile
    volumes:
      - ./nest:/app  # Mount nest folder for live development
      - /app/node_modules  # Anonymous volume for node_modules
      - ./next/dist:/app/public  # Serve next build
      # Windows-specific volumes (will be ignored on Linux)
      - /dev/bus/usb:/dev/bus/usb  # USB device access
    networks:
      - s-pavilion-network
    restart: unless-stopped
    command: sh -c "npm install && npm run start:dev"

  # MediaMTX RTSP to WebRTC/HLS converter
  mediamtx:
    image: bluenviron/mediamtx:latest
    container_name: mediamtx
    environment:
      TZ: Asia/Seoul
    ports:
      - "9554:8554"  # RTSP (using 9554 on host to avoid Windows port conflicts)
      - "8889:8889"  # WebRTC
      - "8887:8890"  # HLS (changed from 8888 to 8887 to avoid Windows port conflict)
      - "8189:8189/udp"  # WebRTC UDP

    profiles:
      - default
      - mock
    volumes:
      - ./mediamtx/mediamtx.yml:/mediamtx.yml:ro
    networks:
      - s-pavilion-network
    restart: unless-stopped

  # YOLOv8 Detection Service
  detection-service:
    build:
      context: ./detection-service
      dockerfile: Dockerfile
    container_name: detection-service
    working_dir: /app
    environment:
      API_URL: http://nest:3000 # NestJS API URL (backend)
      RTSP_URL: rtsp://mediamtx:8554/camera # MediaMTX RTSP URL to ingest video stream
      CAMERA_INDEX: ${CAMERA_INDEX:-0}  # Allow override for Windows webcam
      CELL_SIZE: 16
      TZ: Asia/Seoul
      # Mock environment variables
      MOCK_MODE: ${MOCK_MODE:-true}  # Changed default to false for hardware access
      USE_GSTREAMER: ${USE_GSTREAMER:-false}
      USE_DETECTION: ${USE_DETECTION:-true}  # Enable YOLOv8 detection
      MOCK_VIDEO_FILE: /app/test-video.mp4
      PLATFORM: ${PLATFORM:-windows} 
    devices:
      - /dev/video0:/dev/video0
    privileged: true  

    group_add:
    - "44"  # video 그룹 (카메라 접근 권한용)
    depends_on:
      - mediamtx
    profiles:
      - default
      - mock
      - hardware
    volumes:
      - ./detection-service:/app
      - /app/__pycache__ 
    networks:
      - s-pavilion-network
    restart: unless-stopped
    command: python -u main.py 


  # Nginx Reverse Proxy (Optional)
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: s-pavilion-nginx
    ports:
      - "80:80"
    depends_on:
      - nest
      - mediamtx
    networks:
      - s-pavilion-network
    restart: unless-stopped
    profiles:
      - with-nginx

volumes:
  postgres:
    driver: local

networks:
  s-pavilion-network:
    driver: bridge
